"""add column about

Revision ID: fa08faa98806
Revises: 1b293b23b88a
Create Date: 2023-03-15 11:20:35.214294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa08faa98806'
down_revision = '1b293b23b88a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('about', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'about')
    # ### end Alembic commands ###
